export default ({
  ctrl,
  informers,
  alarms,
  analitics,
  brokes,
  ecodes,
  meas,
  journals,
  statuses,
  services,
  usrs,
  viewgrps,
}) => {
  const {
    devs,
    cameras,
    controllers,
    stats,
    grps,
    modes,
    pass,
    pickshit,
  } = ctrl;
  return {
    alarms,
    analitics,
    brokes,
    cameras,
    controller: ctrl,
    controllers,
    devicesgroups: Object.values(viewgrps),
    devices: devs,
    errors: Object.values(ecodes),
    faces: devs.reduce((acc, device) => acc.concat(Object.values(device.dfaces)), []),
    informers,
    journals,
    modes: Object.values(modes),
    pickinglist: Object.values(pickshit),
    devicepassport: pass,
    services,
    statuses,
    users: usrs,
    viewgroups: Object.values(viewgrps),
  };
};
